### ISSUE TITLE
一点儿建议

### ISSUE THREAD

**Issue by LubinLew** [sun977/linuxcheckshoot#3]
应该配套一个busybox，脚本里的命令尽量用busybox代替，一些挖矿等恶意软件会替换top、ps等命令，及早发现异常。
像ifconfig/netstat 等过时的命令，在稍微新一点的系统中是没有的，基本都是 ip 命令。

检查似乎都是基于 centos 系列的，不兼容 ubuntu ，例如防火墙等， 很多新的系统已经使用 nftables 不使用 iptalbes。

**Comment by sun977** [comment]
后续升级正有此意向，感谢建议
